name: Build Magisk Nova

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk Nova Artifacts
    runs-on: macos-14
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          is-asset-build: true

      - name: Build release
        run: ./build.py -vr all

      - name: Stop gradle daemon
        run: ./app/gradlew --stop

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Magisk-32.8-Nova
          path: out
          
